version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: omise_prod
    volumes:
      - db:/var/lib/postgresql/data

  web:
    build: .

    environment:
      DATABASE_URL: "postgres://postgres:postgres@db/omise_prod?sslmode=disable"

    ports:
      - 3001:3000

    depends_on:
      - db

volumes:
  db:
